name: Build Postcompiler
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  freeze:
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact-name: 'win64'
            python-version: '3.11'
            arch: 'x64'
            os: 'windows-latest'
#          - artifact-name: 'linux64'
#            python-version: '3.11'
#            arch: 'x64'
#            os: 'ubuntu-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}-${{ matrix.arch }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install srctools
        run: |
          python -m pip install -U setuptools pip wheel
          python -m pip install -r requirements.txt
      - name: FGD build and folder copy
#        run: bash ./build_p2ce.sh
        run: cmd /c build_p2ce.bat
      - name: Freeze application
        run: python -m PyInstaller --distpath ../build/bin/win64 -y ../postcompiler.spec
        working-directory: ./src/
      - name: Zip hammeraddons_${{ matrix.artifact-name }}
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: ./build/
          filename: 'hammeraddons_${{ matrix.artifact-name }}.zip'
      - name: Artifact upload (tag)
        uses: actions/upload-artifact@v3
        if: github.event_name == 'create'
        with:
          name: hammeraddons_${{ github.event.inputs.version }}_${{ matrix.artifact-name }}
          path: ./build/hammeraddons_${{ matrix.artifact-name }}.zip
          if-no-files-found: error
      - name: Artifact upload (hash)
        uses: actions/upload-artifact@v3
        if: github.event_name != 'create'
        with:
          name: hammeraddons_${{ github.event.inputs.version }}_${{ matrix.artifact-name }}
          path: ./build/hammeraddons_${{ matrix.artifact-name }}.zip
          if-no-files-found: error

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: |
            ./build/hammeraddons_${{ matrix.artifact-name }}.zip
          fail_on_unmatched_files: true
